/**
 * arm_foc.cpp - tonearm gimbal-motor FOC implementation (TIM3 3-PWM, voltage mode).
 *
 * Mirror of foc.cpp for the SECOND motor. See arm_foc.h for the plan and the differences
 * (TIM3/edge-aligned, ARM_EN/ARM_FAULT, AS5048A 14-bit encoder on SPI2). The control step lives in
 * on_update(), dispatched once per TIM3 PWM period from the shared HAL_TIM_PeriodElapsedCallback in
 * foc.cpp (which branches on htim->Instance == TIM3).
 */
#include "arm_foc.h"
#include "tim.h" /* htim3, generated by CubeMX */
#include "gpio.hpp"
#include "as5048a.h" /* tonearm commutation encoder, read in the closed-loop ISR */
#include <cmath>

namespace arm_foc {
namespace {

/* PWM period: TIM3 edge-aligned (up-counting), ARR=4199 @ 84 MHz -> 20 kHz, one update/period. */
constexpr float kPwmFreq = 20000.0f;
constexpr float kDt      = 1.0f / kPwmFreq;

constexpr float kPi      = 3.14159265358979f;
constexpr float kTwoPi   = 2.0f * kPi;
constexpr float kHalfPi  = 0.5f * kPi;
constexpr float kSqrt3_2 = 0.86602540378f;

/* DRV8313 control lines. EN is active-high; nFAULT is active-low. */
const gpio::OutputPin en{ARM_EN_GPIO_Port, ARM_EN_Pin, /*active_high=*/true};
const gpio::InputPin  nfault{ARM_FAULT_GPIO_Port, ARM_FAULT_Pin, /*active_high=*/false};

/* Control state (read/written in the ISR; single-writer, so plain is fine on M4). */
volatile Mode  g_mode = Mode::Idle;
float g_theta_el      = 0.0f;  /* electrical angle, rad [0, 2pi) */
float g_vel_el        = 0.0f;  /* commanded electrical velocity, rad/s (open-loop) */
float g_hold_el       = 0.0f;  /* fixed electrical angle to park at (Align mode) */
float g_uq            = 0.0f;  /* commanded q-axis voltage (ClosedLoop mode) */
float g_theta_mech    = 0.0f;  /* latest measured mechanical angle, rad (ClosedLoop cache) */

constexpr float kCountToRad = kTwoPi / 16384.0f; /* AS5048A 14-bit count -> rad */

/* Velocity loop runs at a sub-rate of the PWM ISR (cleaner velocity estimate). */
constexpr int   kVelDiv = 20;                 /* every 20 ticks -> 1 kHz */
constexpr float kVelDt  = kVelDiv * kDt;       /* 1 ms */
float g_pos_cont      = 0.0f;  /* unwrapped continuous mechanical position, rad */
float g_raw_prev      = 0.0f;  /* previous raw mechanical angle, rad (for unwrap) */
float g_pos_prev      = 0.0f;  /* position at last velocity-loop tick */
float g_vel           = 0.0f;  /* estimated mechanical velocity, rad/s */
float g_integ         = 0.0f;  /* velocity-loop integral term */
int   g_vel_count     = 0;     /* sub-rate counter */
bool  g_resync        = false; /* prime g_raw_prev on the first sample after a (re)start */
float g_pos_target    = 0.0f;  /* commanded position, rad (Position mode) */

/* --- Sine lookup, built once in init(). 256 entries + 1 guard for linear interpolation. --- */
constexpr int kLut = 256;
float g_sin[kLut + 1];

inline float wrap2pi(float a)
{
    while (a >= kTwoPi) a -= kTwoPi;
    while (a < 0.0f)    a += kTwoPi;
    return a;
}

inline float fast_sin(float a)
{
    a = wrap2pi(a);
    float idx = a * (kLut / kTwoPi);
    int   i   = static_cast<int>(idx);
    float f   = idx - i;
    return g_sin[i] + f * (g_sin[i + 1] - g_sin[i]);
}

inline float fast_cos(float a) { return fast_sin(a + kHalfPi); }

inline float clamp01(float x) { return x < 0.0f ? 0.0f : (x > 1.0f ? 1.0f : x); }

/* Read the AS5048A, cache the mechanical angle, and accumulate unwrapped position. */
inline void sample_encoder()
{
    as5048a::Reading r;
    as5048a::read(r);
    if (!r.parity_ok) return; /* bad/timed-out read: hold last good angle, skip this tick */
    float raw = static_cast<float>(r.angle) * kCountToRad;

    if (g_resync) { g_raw_prev = raw; g_resync = false; } /* avoid a bogus first delta */
    float d = raw - g_raw_prev;          /* unwrap across the 0/2pi seam */
    if (d >  kPi) d -= kTwoPi;
    if (d < -kPi) d += kTwoPi;
    g_pos_cont += d;
    g_raw_prev  = raw;

    g_theta_mech = raw;
    g_theta_el   = mech_to_electrical(raw);
}

inline void write_duty(float da, float db, float dc)
{
    uint32_t arr = __HAL_TIM_GET_AUTORELOAD(&htim3);
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_1, static_cast<uint32_t>(clamp01(da) * arr));
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_2, static_cast<uint32_t>(clamp01(db) * arr));
    __HAL_TIM_SET_COMPARE(&htim3, TIM_CHANNEL_3, static_cast<uint32_t>(clamp01(dc) * arr));
}

}  // namespace

void init()
{
    for (int i = 0; i <= kLut; ++i)
        g_sin[i] = sinf(kTwoPi * i / kLut);

    disable();              /* EN low before the bridge can switch */
    write_duty(0.5f, 0.5f, 0.5f); /* idle at mid-rail (zero phase-to-phase voltage) */

    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1);
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2);
    HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3);
    __HAL_TIM_ENABLE_IT(&htim3, TIM_IT_UPDATE); /* fire on_update() each period */
}

void enable()  { en.on();  }
void disable() { en.off(); }

bool faulted() { return nfault.active(); }

void set_phase_voltage(float Ud, float Uq, float theta_el)
{
    float c = fast_cos(theta_el);
    float s = fast_sin(theta_el);

    /* inverse Park (rotating dq -> stationary alpha/beta) */
    float Ualpha = Ud * c - Uq * s;
    float Ubeta  = Ud * s + Uq * c;

    /* inverse Clarke (alpha/beta -> 3 phase voltages) */
    float Ua = Ualpha;
    float Ub = -0.5f * Ualpha + kSqrt3_2 * Ubeta;
    float Uc = -0.5f * Ualpha - kSqrt3_2 * Ubeta;

    /* sinusoidal modulation: center each phase at 50% duty, scale by the bus voltage */
    float inv = 1.0f / supply_voltage;
    write_duty(0.5f + Ua * inv, 0.5f + Ub * inv, 0.5f + Uc * inv);
}

void set_open_loop_electrical_velocity(float elec_rad_s)
{
    g_vel_el = elec_rad_s;
    g_mode   = Mode::OpenLoop;
    enable();
}

void set_open_loop_velocity(float mech_rad_s)
{
    set_open_loop_electrical_velocity(mech_rad_s * pole_pairs);
}

void hold_electrical_angle(float theta_el)
{
    g_hold_el = wrap2pi(theta_el);
    g_mode    = Mode::Align;
    enable();
}

float mech_to_electrical(float theta_mech)
{
    return wrap2pi(direction * pole_pairs * (theta_mech - zero_elec_offset));
}

void set_closed_loop_torque(float uq)
{
    g_uq     = uq;
    g_resync = true;
    g_mode   = Mode::ClosedLoop;
    enable();
}

void set_closed_loop_velocity(float target_mech_rad_s)
{
    vel_target  = target_mech_rad_s;
    g_integ     = 0.0f;
    g_vel       = target_mech_rad_s; /* seed the filter at target to soften startup */
    g_pos_prev  = g_pos_cont;
    g_vel_count = 0;
    g_resync    = true;
    g_mode      = Mode::Velocity;
    enable();
}

void set_target_position(float target_mech_rad)
{
    g_pos_target = target_mech_rad;
    g_vel        = 0.0f;
    g_pos_prev   = g_pos_cont; /* seed the velocity estimate cleanly */
    g_vel_count  = 0;
    g_resync     = true; /* prime the unwrap so the first sample does not jump g_pos_cont */
    g_mode       = Mode::Position;
    enable();
}

void jog(float delta_mech_rad)
{
    /* Relative to wherever the carriage is right now. g_pos_cont is the same accumulator the loop
     * drives, so targeting +delta moves the motor by delta from its current position. */
    set_target_position(g_pos_cont + delta_mech_rad);
}

float position()        { return g_pos_cont; }
float position_target() { return g_pos_target; }
bool  position_settled()
{
    float e = g_pos_target - g_pos_cont;
    if (e < 0.0f) e = -e;
    return e <= pos_tol_rad;
}

float mechanical_angle() { return g_theta_mech; }
float velocity()         { return g_vel; }
float applied_uq()       { return g_uq; }

void stop()
{
    g_mode = Mode::Idle;
    disable();
    write_duty(0.5f, 0.5f, 0.5f);
}

Mode  mode()             { return g_mode; }
float electrical_angle() { return g_theta_el; }

void on_update()
{
    switch (g_mode) {
    case Mode::OpenLoop:
        g_theta_el = wrap2pi(g_theta_el + g_vel_el * kDt);
        set_phase_voltage(0.0f, voltage_limit, g_theta_el);
        break;

    case Mode::Align:
        /* Pure d-axis voltage parks the rotor's magnetic axis at g_hold_el. */
        g_theta_el = g_hold_el;
        set_phase_voltage(align_voltage, 0.0f, g_hold_el);
        break;

    case Mode::ClosedLoop:
        sample_encoder();
        set_phase_voltage(0.0f, g_uq, g_theta_el);
        break;

    case Mode::Velocity:
        sample_encoder();
        /* PI velocity loop at the sub-rate; back-calculation anti-windup on the Uq clamp. */
        if (++g_vel_count >= kVelDiv) {
            g_vel_count = 0;
            float raw_vel = (g_pos_cont - g_pos_prev) / kVelDt;
            g_pos_prev = g_pos_cont;
            g_vel += vel_lpf_a * (raw_vel - g_vel); /* EMA low-pass the estimate */

            float err = vel_target - g_vel;
            g_integ += err * kVelDt;
            float u = vel_kp * err + vel_ki * g_integ;
            if (u >  uq_limit) { u =  uq_limit; if (vel_ki > 0.0f) g_integ = ( uq_limit - vel_kp * err) / vel_ki; }
            if (u < -uq_limit) { u = -uq_limit; if (vel_ki > 0.0f) g_integ = (-uq_limit - vel_kp * err) / vel_ki; }
            g_uq = u;
        }
        set_phase_voltage(0.0f, g_uq, g_theta_el);
        break;

    case Mode::Position:
        sample_encoder();
        /* PD position servo at the sub-rate: Uq = pos_kp*err - pos_kd*velocity, clamped. The D term
         * uses the same EMA velocity estimate as the velocity loop. */
        if (++g_vel_count >= kVelDiv) {
            g_vel_count = 0;
            float raw_vel = (g_pos_cont - g_pos_prev) / kVelDt;
            g_pos_prev = g_pos_cont;
            g_vel += vel_lpf_a * (raw_vel - g_vel);

            float err = g_pos_target - g_pos_cont;
            float u = pos_kp * err - pos_kd * g_vel;
            if (u >  uq_limit) u =  uq_limit;
            if (u < -uq_limit) u = -uq_limit;
            g_uq = u;
        }
        set_phase_voltage(0.0f, g_uq, g_theta_el);
        break;

    case Mode::Idle:
    default:
        break;
    }
}

}  // namespace arm_foc
